export const geoLocationTypes = {
  GET_GEO_LOCATION_SUCCESS: "GET_GEO_LOCATION_SUCCESS",
  GET_GEO_LOCATION_FAILED: "GET_GEO_LOCATION_FAILED",
  GET_GEO_LOCATION_PENDING: "GET_GEO_LOCATION_PENDING",
  FETCH_WEATHER_PENDING: "FETCH_WEATHER_PENDING",
  FETCH_WEATHER_SUCCESS: "FETCH_WEATHER_SUCCESS",
  FETCH_WEATHER_FAILED: "FETCH_WEATHER_FAILED",
};
